include (":feature:afeatureimpl")
include (":feature:afeatureapi")
include (":feature:bfeatureimpl")
include (":feature:bfeatureapi")
include (":feature:cfeatureimpl")
include (":feature:cfeatureapi")
include (":feature:dfeatureimpl")
include (":feature:dfeatureapi")
include (":feature:efeatureimpl")
include (":feature:efeatureapi")

include (":core:modulinjection")
include (":core:commonimpl")
include (":core:commonapi")
include (":core:database")
include (":core:networkimpl")
include (":core:networkapi")

include (":app")
rootProject.name = "MyApp"